name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Test:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Pony & 3rd Party Dependencies
      run: brew install corral libressl pcre2
    - name: Build
      run: corral fetch & make
