name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Pony & 3rd Party Dependencies
      run: |
        sudo apt-get install -y libssl-dev
        bash -c "$(curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/ponylang/ponyup/latest-release/ponyup-init.sh)"
        export PATH=$PATH:/home/runner/.local/share/ponyup/bin
        ponyup update ponyc release
        ponyup update corral release
        echo "/home/runner/.local/share/ponyup/bin" >> $GITHUB_PATH
    - name: Build
      run: |
        corral fetch
        make
