name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Cache Corral Downloaded Depenencies
      uses: actions/cache@v3
      with:
        path: ~/work/presentation-service-pony/presentation-service-pony/_repos
        key: corral-${{ hashFiles('~/work/presentation-service-pony/lock.json') }}

    - name: Setup Pony SDK
      run: |
        bash -c "$(curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/ponylang/ponyup/latest-release/ponyup-init.sh)"
        export PATH=$PATH:/home/runner/.local/share/ponyup/bin
        ponyup update ponyc release
        ponyup update corral release
        echo "/home/runner/.local/share/ponyup/bin" >> $GITHUB_PATH

    - name: Build
      run: |
        corral fetch
        corral run -- ponyc -Dopenssl_1.1.x -o build/release presentation_service
