name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache ponyup Downloads
      uses: actions/cache@v3
      with:
        path: /home/runner/.local/share/ponyup
        key: ${{ runner.os }}-ponyup-${{ hashFiles('Makefile') }}
        restore-keys: |
          ${{ runner.os }}-ponyup-

    - name: Cache Corral Depenencies
      uses: actions/cache@v3
      with:
        path: _repos
        key: ${{ runner.os }}-corral-${{ hashFiles('**/lock.json') }}
        restore-keys: |
          ${{ runner.os }}-corral-

    - name: Setup Pony SDK
      run: |
        if [ ! -d "/home/runner/.local/share/ponyup" ]; then
          bash -c "$(curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/ponylang/ponyup/latest-release/ponyup-init.sh)"
        fi
        export PATH=$PATH:/home/runner/.local/share/ponyup/bin
        ponyup update ponyc release
        ponyup update corral release
        echo "/home/runner/.local/share/ponyup/bin" >> $GITHUB_PATH

    - name: Build
      run: |
        corral fetch
        corral run -- ponyc -Dopenssl_1.1.x -o build/release presentation_service
