name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Pony & 3rd Party Dependencies
      run: sudo apt-get install -y libssl-dev corral
    - name: Build
      run: corral fetch & make
